#      
# Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mil-wit
  name: mil-wit
spec:
  #
  # ReplicaSet
  #
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mil-wit
  template:
    #
    # Pod
    #
    metadata:
      labels:
        app.kubernetes.io/name: mil-wit
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: mil-d-wit-sa
      containers:
      - image: ghcr.io/pagopa/mil-wit:refs_heads_main
        name: mil-wit
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mil-wit-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mil-wit
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: mil-wit-ingress
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: mil-wit-service
#            port:
#              number: 8080
